### ISSUE TITLE
spider automation test

### ISSUE THREAD

**Issue by jvanz** [okfn-brasil/querido-diario#148]
I believe we should find a way to run some kind of automatic testing in the spiders. My first idea is use the github actions to run the spiders for a while and check if it downloads some files. If it does, great, the test passes. Otherwise, it fails. 

Furthermore, if the test failed, we can use the github action to open an issue automatically.

**Comment by vitorbaptista** [comment]
For the parsers, I like the way @pauloabelha and I wrote the parser on https://github.com/okfn-brasil/diario-oficial/pull/106 following a TDD style.

For the spiders, I think we'd be better off monitoring than testing.

Let's take a step back. The problem we're facing is how to ensure that the scrapers are healthy and downloading the data as normal. For example, how could we notice if a public body changed its gazette format?

We could solve it using tests. There are a few tools that help saving and replaying an HTML response (personally I like [VCR.py](https://github.com/kevin1024/vcrpy)). We could write a test that downloads a gazette's webpage and parses it, checking the results. In this case, we should also write a test that downloads the *latest* gazette and tries to parse it, as I imagine a common change will be a new gazette template.

This would work, and a test suite can be very useful while developing the scraper (if it's easy enough to set up).

Another possibility is simply to add monitoring to our scrapers. If I expect 100 scrapers to download 100 new gazettes per day, if one day only 95 gazettes are downloaded, I know something went wrong. This IMHO would be an easier way to increase the pipeline's reliability.

Just to be clear, ideally we would have both: testing and monitoring. Testing focusing more on writing the scrapers, TDD-style (as in #106), while monitoring focus on checking if the pipeline is healthy and nothing broke because of i.e. a website structure change.

For monitoring, I'd suggest taking a look at https://www.datadoghq.com/. For testing, VCR-py is great, and if we follow the [Functional Core, Imperative Shell](https://www.destroyallsoftware.com/screencasts/catalog/functional-core-imperative-shell) pattern, we could just save HTMLs and pass them on to be parsed.

**Comment by rennerocha** [comment]
Testing spiders is not an easy task as you have absolutely no control over the content you receive from the websites you are scraping so we can't think of tests the same way as other systems.

What can be tested? Processors and pipelines are good candidates for regular testing. Parsing methods don't.

Caching the responses (using VCR.py or any other kind of library that stores it) may be useful only for development, and I don't see any real gain to keep it in the project, as they are very fragile tests. Any change in the website layout, the tests will be outdated and useless.

We need to monitor the spiders, not test them. I suggest you to take a look at [Spidermon](https://spidermon.readthedocs.io/en/latest/), a library that was designed specially for Scrapy spiders monitoring (I am the maintainer of this library).

Working on adding useful stats in the job execution and good monitors, it would be possible to improve the monitoring of the spiders and receive notifications when something looks weird. You can have different monitors for different spiders, and common monitors for all spiders.

**Comment by jvanz** [comment]
Sorry, I used the wrong the terms. When I mentioned tests I meant run the  spiders to see if can downloaded the files. It's more monitoriong the spider then "test" them as you both said. The goal is just get a notification when the spider cannot download something from the websites.

**Comment by jvanz** [comment]
Spidermon  seems to be the way to go.

**Comment by jvanz** [comment]
Closing this in favor of #248
