### ISSUE TITLE
Create date filter

### ISSUE THREAD

**Issue by EvertonTomalok** [okfn-brasil/querido-diario#172]
Hello guys, how we talked some days ago, we found a potential problem to integrate OKFN's projects to Jusbrasil stack of Brazilian data extraction.

We discussed some points about it, and we suggested some changes in the project:

- Create a way where is possible to pass a date to filter results.
- Based on these filters, make fewer requests than possible.
- [Minor] Return PDF's links and more information if possible, like publication date, etc.

An important point to remember is that we are available to help with coding theses changes, if necessary.

**Comment by jvanz** [comment]
Hi Everton!

I'm sorry for the delay. I was stuck in a course that I was doing and could not reach my TODO list item to give you some feedback. Let's do it now:


>     * Create a way where is possible to pass a date to filter results.
>     * Based on these filters, make fewer requests than possible.

I would like to talk with you about this topic. You said you would like to avoid request, wich is good. But wanna to check if you want to avoid the requests to the web pages OR the request to download the files. As I said in the call, our current implementations visit all the pages. But it does not download all the files every time. We have [cache](https://github.com/okfn-brasil/diario-oficial/blob/master/processing/data_collection/gazette/settings.py#L11) in place witch prevent us to download a file already downloaded. Furthermore, we have a simple [date filter](https://github.com/okfn-brasil/diario-oficial/blob/master/processing/data_collection/gazette/pipelines.py#L43) already in use. This date filter is not working for the FECAM spiders. But I plan to add that soon to make it concise with the other spiders.

Both solutions are very simple. But it works so far. I would love to see a mechanism to avoid visit all the web pages. That will be awesome. We can talk about that more deeply.

>     * [Minor] Return PDF's links and more information if possible, like publication date, etc.

At the first glance, I believe this will be easy. Scrapy has way to export the scraped data. We can add something to export some file with the data instead of download the files in the disk.

**Comment by giuliocc** [comment]
[BaseGazetteSpider](https://github.com/okfn-brasil/querido-diario/blob/d217c84df26a1547e18f6aad98d3f6f5ff7029c9/data_collection/gazette/spiders/base/__init__.py#L7) already has an `start_date` and `end_date` argument parsers now.

`start_date` in particular is being used in all spiders running in production and making as few requests as possible when a date is provided.

I'm closing this issue since I believe it's been fulfilled :)
