### ISSUE TITLE
Review use of scrapy_deltafetch middleware

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#219]
scrapy_deltafetch middleware seems useful to avoid scraping the same page more than once. However, today when working with [Macapa](https://github.com/okfn-brasil/querido-diario/pull/217) spider, it didn't worked well (it skiped some pages that I wanted to scrape some missing items). Maybe we should review if this middleware is really useful.

**Comment by jvanz** [comment]
Yeah, we definitely need a better cache. I've enabled this one just to save some bandwidth. But it is not the best middleware.  I would love to build a smart cache middleware to avoid waste requests for data that we already fetched in the past. But this will require some kind of persistence storage and some mechanism to detect old requests. Actually, there is issue (#172 ) briefly asking for this feature.

**Comment by giuliocc** [comment]
This middleware already uses Scrapy's `request_fingerprint` which is pretty useful for this purpose. It's builtin `DELTAFETCH_RESET` seems over the top for this use case since it truncates the entire database. Maybe we could fork it and add an option like `deltafetch_ignore` to be passed in the request's `meta` to be able to redo those requests?

**Comment by jvanz** [comment]
I do not know. I've not spent to much time thinking about that. I think the cache should be smarter than that. It should detect when it should allow a request automatically. For instance, if necessary, after X time redo the request. Or detect some kind of inconsistency and allow the request to be perform. But I am not sure if that really necessary. Your approach can be a good starting point.

One thing that must be addressed is the backend storage system. Currently it's just a file in the disk (sqlite maybe?). Which is not scalable and will not work if we move the spider to another machine or directory. IMHO, a better backend storage is also necessary

**Comment by giuliocc** [comment]
Then maybe a middleware based on the httpcache middleware with a custom storage backend could be better and easier to implement.

> For instance, if necessary, after X time redo the request.

What kind of problem would we be trying to solve being able to redo the request after X time? A precaution against not knowing if the gazettes are modified after they've been scraped?

> Or detect some kind of inconsistency and allow the request to be perform. But I am not sure if that really necessary.

Maybe looking into some content of the response? The httpcache's default policy does something like that.

**Comment by jvanz** [comment]
> Then maybe a middleware based on the httpcache middleware with a custom storage backend could be better and easier to implement.

Sounds reasonable. But a P.O.C. and more research may be necessary. Specially checking how scrapy middleware works. 

> What kind of problem would we be trying to solve being able to redo the request after X time? A precaution against not knowing if the gazettes are modified after they've been scraped?

Yeah. That the first thing that come to my mind. But this can be added to the cache after. 

> Maybe looking into some content of the response? The httpcache's default policy does something like that.

I do not know if I understand correctly you said. You cannot check only the response. Otherwise, you will perform the request which is what we are trying to avoid. Right? The best would be based on the request data,  checks if we already crawled that page/file.

Another thing that we need to find a solution is what we do when the detect a duplicate request. Will we store the page content and return it to the user? I think we cannot just drop any duplicate request. Because we have spiders which need the web pages to check which pages should be crawled. If we return always the same page, the spider will not download the latest files.



One thing that just came to my mind is a CDN. If the Digital Ocean has a local CDN we **may** rely on the cloud CDN. Thus, the request will not leave the data center. **But I do not know if this is the case.** This is something that just crossed my mind. It may worth to check if it is plausible or not.

**Comment by giuliocc** [comment]
> Sounds reasonable. But a P.O.C. and more research may be necessary. Specially checking how scrapy middleware works.

Agreed :)

> Yeah. That the first thing that come to my mind. But this can be added to the cache after.

Also agreed ;)
 
> > Maybe looking into some content of the response? The httpcache's default policy does something like that.
> 
> I do not know if I understand correctly you said. You cannot check only the response. Otherwise, you will perform the request which is what we are trying to avoid. Right? The best would be based on the request data, checks if we already crawled that page/file.

I was talking about the response which we could already see when _making_ the request that could be cached. But I can't think of any use case, I don't know why I talked about it. Forget it hehehe.

> Another thing that we need to find a solution is what we do when the detect a duplicate request. Will we store the page content and return it to the user? I think we cannot just drop any duplicate request. Because we have spiders which need the web pages to check which pages should be crawled. If we return always the same page, the spider will not download the latest files.
> 
> One thing that just came to my mind is a CDN. If the Digital Ocean has a local CDN we **may** rely on the cloud CDN. Thus, the request will not leave the data center. **But I do not know if this is the case.** This is something that just crossed my mind. It may worth to check if it is plausible or not.

Huuum. Seems wild. I think that cache-like behaviour is the way to go too instead of dropping.

**Comment by jvanz** [comment]
> Huuum. Seems wild. I think that cache-like behaviour is the way to go too instead of dropping.

Yeap, CDN can act like a cache in many cases. That's why I suggested investigate this path.

**Comment by rennerocha** [comment]
Reducing the amount of requests is not something easy to solve. It is not the request, but its response that matters.
The same request may return a different set of data after some days, so it is not 

[This pipeline](https://github.com/okfn-brasil/querido-diario/blob/main/processing/data_collection/gazette/pipelines.py#L17) filters the gazettes returned, so we don't download files that we already have. Maybe this is enough for now and we can just remove this middleware. When we put hundreds of spiders running in production we can reevaluate if this is a good solution. What do you think?
