### ISSUE TITLE
proposal: Documentation / Wiki

### ISSUE THREAD

**Issue by alexandrevicenzi** [okfn-brasil/querido-diario#266]
In #195 there are a few limitations in the current implementation and we should document it, as well as document a lot of other things that I don't seem to find anywhere.

The idea would be to create a GitHub Wiki or perhaps Sphinx documentation that could be hosted anywhere.

Every project should have documentation that addresses limitations, behaviors, why decisions were made, and everything else, so once someone joins the project they would have a place to understand why the project is the way it is and not file issues of weird things because they do not understand.

**Comment by alexandrevicenzi** [comment]
@jvanz @giuliocc what would be the best format for this type of documentation?

GitHub Wiki is good that you don't need to send any PRs, it's quick to update.
Sphinx should live with the code and should be more up to date, change the code and the doc at the same time.

**Comment by giuliocc** [comment]
My personal opinion is that the closer the documentation is to the actual code the better. That's why I prefer docstrings and tools that use them to generate static docs. Sphinx has ways of rendering images too and such (sometimes I find that really valuable for spiders).

I think that docs would be cool to have. I'm all for it. But we have to consider if now is the right moment.

I'm mentioning @rennerocha too for his experience with spider projects and documentation.

**Comment by alexandrevicenzi** [comment]
@giuliocc based on my personal experience, tests, and documentation are things that should be in place since the start of the project.

I can start looking into Sphinks if that's the case, I personally find it also useful, close to the code is usually the best approach.

Wiki would still be interesting if we want to have some sort of FAQ or tips on how to run on Linux, Windows, and so on.

**Comment by jvanz** [comment]
As we discussed in other communication channels, I think we should have a `/doc` in the repo with the documentation. ;)

**Comment by alexandrevicenzi** [comment]
I'll start it soon, and send a WIP for review.

**Comment by rennerocha** [comment]
Documentation is located in https://github.com/okfn-brasil/querido-diario-comunidade now.
