### ISSUE TITLE
Problem with pre-commit

### ISSUE THREAD

**Issue by adorilson** [okfn-brasil/querido-diario#368]
When I ran `git commit`, I got the below:

```
$ git commit
An unexpected error has occurred: OSError: [Errno 8] Exec format error: '/home/adorilson/workspace/querido-diario/.git/hooks/pre-commit.legacy'
Check the log at /home/adorilson/.cache/pre-commit/pre-commit.log
```

My pre-commit.log

```console
$ cat /home/adorilson/.cache/pre-commit/pre-commit.log
### version information

\```
pre-commit version: 2.8.2
sys.version:
    3.6.9 (default, Oct  8 2020, 12:12:24) 
    [GCC 8.4.0]
sys.executable: /home/adorilson/workspace/querido-diario/.venv/bin/python3
os.name: posix
sys.platform: linux
\```

### error information

\```
An unexpected error has occurred: OSError: [Errno 8] Exec format error: '/home/adorilson/workspace/querido-diario/.git/hooks/pre-commit.legacy'
\```

\```
Traceback (most recent call last):
  File "/home/adorilson/workspace/querido-diario/.venv/lib/python3.6/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/home/adorilson/workspace/querido-diario/.venv/lib/python3.6/site-packages/pre_commit/main.py", line 354, in main
    args=args.rest[1:],
  File "/home/adorilson/workspace/querido-diario/.venv/lib/python3.6/site-packages/pre_commit/commands/hook_impl.py", line 211, in hook_impl
    retv, stdin = _run_legacy(hook_type, hook_dir, args)
  File "/home/adorilson/workspace/querido-diario/.venv/lib/python3.6/site-packages/pre_commit/commands/hook_impl.py", line 43, in _run_legacy
    return subprocess.run(cmd, input=stdin).returncode, stdin
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/adorilson/workspace/querido-diario/.git/hooks/pre-commit.legacy'
\```

```

I'm using Ubuntu 18.04 LTS.

Searching a solution, I have found the [isort --recursive  argument can be removed](https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/#-recursive-or-rc)  (in Makefile). This don't resolve the problem, but is a few improvement in pre-commit context.

**Comment by giuliocc** [comment]
@adorilson I think the cause for this has to do with updating the project to use `pre-commit` while having the old setup not overwritten. I'm guessing you already had a `.git/hooks/pre-commit` file which contained only the `make check` command (provided by the old `make setup`).

When installing `pre-commit`, it automatically copied the old content to `.git/hooks/pre-commit.legacy` and created a new `.git/hooks/pre-commit`. That can be avoided if when installing `pre-commit` and it detects an existent `.git/hooks/pre-commit` you choose to overwrite, but I guess that was not the case.

Finally, the error is caused because `pre-commit` is trying to run `.git/hooks/pre-commit.legacy` and it doesn't have a shebang, which causes a format error.

Try erasing the `.git/hooks/pre-commit.legacy` file and see if it works out :)

**Comment by jvanz** [comment]
@adorilson have you tried the procedure suggested by @giuliocc ?

**Comment by adorilson** [comment]
> @adorilson have you tried the procedure suggested by @giuliocc ?

I tried right now. And it works.
